from preprocessing.consts import SOURCES_DIR

YEAST_SOURCES_DIR = SOURCES_DIR / 'yeast'
YEAST_BREITKREUTZ_SOURCES_DIR = YEAST_SOURCES_DIR / 'breikreutz'
YEAST_GENERATED_SOURCES_DIR = YEAST_SOURCES_DIR / 'generated'

RAW_YEAST_BIOGRID_PATH = YEAST_SOURCES_DIR / 'BIOGRID-ORGANISM-Saccharomyces_cerevisiae_S288c-4.4.199.tab3.txt'
GENERATED_YEAST_BIOGRID_NET_PATH = YEAST_GENERATED_SOURCES_DIR / 'biogrid_net.gpickle'

RAW_BREITKREUTZ_ANNOTATIONS_DATA_PATH = YEAST_BREITKREUTZ_SOURCES_DIR / 'Breitkreutz_annotations.txt'
GENERATED_BREITKREUTZ_ANNOTATIONS_PATH = YEAST_GENERATED_SOURCES_DIR / 'breitkeurtz_annotations.json'

RAW_BREITKREUTZ_EXPRESSIONS_DATA_PATH = YEAST_BREITKREUTZ_SOURCES_DIR / 'Breitkreutz_experiments_expressions.cdt'
GENERATED_BREITKREUTZ_EXPRESSIONS_PATH = YEAST_GENERATED_SOURCES_DIR / 'breitkeurtz_expressions.json'
