from preprocessing.consts import SOURCES_DIR

HUMAN_SOURCES_DIR = SOURCES_DIR / 'human'
HUMAN_SILVERBUSH_SOURCES_DIR = HUMAN_SOURCES_DIR / 'silverbush_d2d'
HUMAN_GENERATED_SOURCES_DIR = HUMAN_SOURCES_DIR / 'generated'

RAW_HUMAN_NET_PATH = HUMAN_SILVERBUSH_SOURCES_DIR / 'kegg.net'
RAW_KEGG_SOURCES_DATA_PATH = HUMAN_SILVERBUSH_SOURCES_DIR / 'kegg_sources.txt'
RAW_KEGG_TARGETS_DATA_PATH = HUMAN_SILVERBUSH_SOURCES_DIR / 'kegg_targets.txt'

GENERATED_HUMAN_NET_PATH = HUMAN_GENERATED_SOURCES_DIR / 'net.gpickle'
GENERATED_EXPERIMENT_PATH = HUMAN_GENERATED_SOURCES_DIR / 'experiment.json'
GENERATED_KEGG_ANNOTATIONS_PATH = HUMAN_GENERATED_SOURCES_DIR / 'kegg_annotations.json'
GENERATED_KEGG_TRUE_DIRECTION_ANNOTATIONS_PATH = HUMAN_GENERATED_SOURCES_DIR / 'kegg_true_direction_annotations.json'
GENERATED_KEGG_FALSE_DIRECTION_ANNOTATIONS_PATH = HUMAN_GENERATED_SOURCES_DIR / 'kegg_false_direction_annotations.json'
